/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SmsViewer.java
 *
 * Created on 11 Ιουν 2009, 9:29:00 μμ
 */
package gui;

/**
 *
 * @author Jimmys Daskalakis
 */
public class SmsViewer extends javax.swing.JFrame {

    private String strXml;
    private String strTxt;
    private String strCsv;

    /** Creates new form SmsViewer */
    public SmsViewer() {
        initComponents();
    }

    public void setXml(String strXml) {
        this.strXml = strXml;
        TextArea.setText(strXml);
    }

    public void setTxt(String strTxt) {
        this.strTxt = strTxt;
        TextArea.setText(strTxt);

    }

    public void setCvs(String strCsv) {
        this.strCsv = strCsv;
        TextArea.setText(strCsv);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();

        setTitle("SMS Viewer");

        TextArea.setColumns(20);
        TextArea.setEditable(false);
        TextArea.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        TextArea.setRows(5);
        jScrollPane1.setViewportView(TextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-585)/2, (screenSize.height-410)/2, 585, 410);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SmsViewer().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea TextArea;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
